

default:
  image: node:latest
  before_script:
    - yarn install --frozen-lockfile
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee --append .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  #TEST_DOCKER_HOST: gmab.net.dr.dk.crt
  GIT_SSL_NO_VERIFY: true

stages:
  - test
  - build
  - release

test:
  script:
    - yarn test

publish:
  stage: release
  script:
    #- export DOCKER_HOST=tcp://${TEST_DOCKER_HOST}:2376
    #- export DOCKER_TLS_VERIFY=1
    #- export DOCKER_CERT_PATH=/etc/docker/certs.d/${TEST_DOCKER_HOST}/
    - cp /etc/gitlab-runner/certs/*.crt /usr/local/share/ca-certificates/ && update-ca-certificates #&& dockerd-entrypoint.sh || exit
    - npx semantic-release --debug
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH